sudo: required
services:
  - docker

before_install:
  - docker build -t haseemsaeed/docker-reactwork -f Dockerfile.dev .

script:
  - docker run haseemsaeed/docker-reactwork npm run test -- --coverage
